### ISSUE TITLE
仓库代码遗漏，未提交

### ISSUE THREAD

**Issue by 0muxi0** [MaybeQHL/v-power#1]
代码提交遗漏了/cli/lib/bin.js ，需要修改一下你的.gitignore里的配置 。
![image](https://user-images.githubusercontent.com/26497065/155913929-1c81673b-f8fb-4216-a5b0-c72e32908e29.png)

**Comment by MaybeQHL** [comment]
1. 打开cli文件夹
` cd ./cli
`
2. 执行构建cli命令
`
 npm run build
`

**Comment by 0muxi0** [comment]
666
