### ISSUE TITLE
打包后的Vue2.x版本组件库缺少style目录

### ISSUE THREAD

**Issue by 0muxi0** [MaybeQHL/v-power#2]
在宿主工程为Vue2.x 的项目 ，组件使用时，会报找不到样式文件的错误。已经在babel.config.js  添加按需加载代码。
![image](https://user-images.githubusercontent.com/26497065/156558071-c8de8fec-5781-4b3c-8916-de021299f28e.png)

**Comment by MaybeQHL** [comment]
本地调试需要
```
yalc publish // 宿主工程
yalc add @maybecode/v-power // 调试工程 

```

**Comment by 0muxi0** [comment]
> 本地调试需要
> 
> ```
> yalc publish // 宿主工程
> yalc add @maybecode/v-power // 调试工程 
> ```

上面的截图是下载你发布到https://www.npmjs.com/ 的资源，在Vue2.x项目中使用按需引入组件的报错，虽然可以放弃按需引入使用全局引入。     尝试看了下源码cli目录下的打包style的代码都没什么问题但打包为V2版本时确实会缺少style目录

**Comment by MaybeQHL** [comment]
好的，确实存在这个问题。

**Comment by MaybeQHL** [comment]
更新版本到`1.0.24`,然后重新看下按需导入的文档（有改变）,看看解决此问题没有。

**Comment by 0muxi0** [comment]
> 

修改V2版本引入css指向路径后可以用的，V3版本可以和原来的保持一致不影响。只是很好奇你改了vant-cli的什么代码导致V2版本打包后，不能生成style文件夹及其文件夹内的资源，我看了打包生成style的核心代码都是一样的，按理说不应该导致V2 V3版本的打包结果不一样。

**Comment by 0muxi0** [comment]
> 更新版本到`1.0.24`,然后重新看下按需导入的文档（有改变）,看看解决此问题没有。

修改V2版本引入css指向路径后可以用的，V3版本可以和原来的保持一致不影响。只是很好奇你改了vant-cli的什么代码导致V2版本打包后，不能生成style文件夹及其文件夹内的资源，我看了打包生成style的核心代码都是一样的，按理说不应该导致V2 V3版本的打包结果不一样。

**Comment by MaybeQHL** [comment]
更新版本到`1.1.0`,已经修复相关问题。按需导入还是从`index.css`修改成以前的`style`目录

**Comment by MaybeQHL** [comment]
如果有兴趣组件相关可以提pr一起开发。
